name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir-version: [1.10.x, 1.9.x, 1.8.x]
        include:
          - elixir-version: 1.10.x
            otp-version: 22.x
          - elixir-version: 1.9.x
            otp-version: 21.x
          - elixir-version: 1.8.x
            otp-version: 20.x
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}

      - uses: actions/cache@v1
        id: plts-cache
        with:
          path: .plts
          key: ${{ runner.os }}-plts-${{ matrix.otp-version }}-${{ matrix.elixir-version }}
          restore-keys: ${{ runner.os }}-plts-${{ matrix.otp-version }}-

      - run: make dependencies
      - run: make plts
      - run: make lint
      - run: make test
